# Generated by Django 3.1.2 on 2020-10-23 16:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201019_1549'),
        ('estagiario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estagiario',
            old_name='status_estagiario',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='estagiario',
            name='descricao_contrato',
        ),
        migrations.RemoveField(
            model_name='estagiario',
            name='dt_fim_contrato',
        ),
        migrations.RemoveField(
            model_name='estagiario',
            name='dt_inicio_contrato',
        ),
        migrations.RemoveField(
            model_name='estagiario',
            name='email_estagiario',
        ),
        migrations.RemoveField(
            model_name='estagiario',
            name='nome_estagiario',
        ),
        migrations.RemoveField(
            model_name='estagiario',
            name='orgao_estagiario',
        ),
        migrations.RemoveField(
            model_name='estagiario',
            name='setor_estagiario',
        ),
        migrations.AddField(
            model_name='estagiario',
            name='contrato',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do contrato'),
        ),
        migrations.AddField(
            model_name='estagiario',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='estagiario',
            name='curso',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.curso', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='estagiario',
            name='documento',
            field=models.FileField(null=True, upload_to='media', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='estagiario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='estagiario',
            name='fim_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Data de término'),
        ),
        migrations.AddField(
            model_name='estagiario',
            name='inicio_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Data de inicio'),
        ),
        migrations.AddField(
            model_name='estagiario',
            name='n_contrato',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número do contrato'),
        ),
        migrations.AddField(
            model_name='estagiario',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome completo'),
        ),
        migrations.AddField(
            model_name='estagiario',
            name='orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.orgao', verbose_name='Orgão'),
        ),
        migrations.AddField(
            model_name='estagiario',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.setor', verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='estagiario',
            name='telefone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='dt_cadastro',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data de cadastro'),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='dt_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='instituicao_edu',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.instituicao', verbose_name='Instituição de ensino'),
        ),
    ]
